/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.amplify;

import com.amplifyframework.AmplifyException;
import com.amplifyframework.analytics.AnalyticsEvent;
import com.amplifyframework.analytics.pinpoint.AWSPinpointAnalyticsPlugin;
import com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin;
import com.amplifyframework.core.Amplify;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;


@Kroll.module(name = "TiAmplify", id = "ti.amplify")
public class TiAmplifyModule extends KrollModule {
    private static final String LCAT = "TiAmplifyModule";

    public TiAmplifyModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }

    @Kroll.method
    public void initialize() {
        try {
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSPinpointAnalyticsPlugin());
            Amplify.configure(TiApplication.getAppCurrentActivity());
        } catch (AmplifyException error) {
            Log.e(LCAT, "Could not initialize Amplify: " + error.getMessage());
        }
    }

    @Kroll.method
    public void log(KrollDict data) {
        AnalyticsEvent.Builder event = AnalyticsEvent.builder();
        event.name(data.getString("eventName"));
        event.addProperty(data.getString("propertyName"), data.getString("propertyValue"));
        Amplify.Analytics.recordEvent(event.build());
    }
}

